name: Update dependencies

on:
  schedule:
    - cron: '30 14,16,17,19 * * MON-FRI'

jobs:
  update-dependencies:
    name: Update dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Update package dependencies
        run: npm update --production

      - name: Commit files if changed
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git add package.json package-lock.json
          git diff-index --quiet HEAD || git commit -m 'chore(deps): update pkg dependencies'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: develop
